[project]
name = "katas"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.12,<4.0"

dependencies = [
    "pytest (>=8.4.2,<9.0.0)",
    "syrupy (>=5.0.0,<6.0.0)",
]

[tool.poetry]
packages = [
    { include = "src" }
]
